name        : perl-archive-zip
version     : 1.57
release     : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PH/PHRED/Archive-Zip-1.57.tar.gz : 4238b4df7e5f244c684dec83f75c0fa56819c01c61f9314c91f6a60fd41d3694
license     :
    - Artistic-Perl-1.0
summary     : Perl Archive::Zip module
component   : programming.perl
description : |
    The Archive::Zip module allows a Perl program to create, manipulate, read, and write Zip archive file
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
