name       : perl-archive-zip
version    : '1.68'
release    : 14
source     :
    - https://cpan.metacpan.org/authors/id/P/PH/PHRED/Archive-Zip-1.68.tar.gz : 984e185d785baf6129c6e75f8eb44411745ac00bf6122fb1c8e822a3861ec650
homepage   : https://metacpan.org/release/Archive-Zip
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl Archive::Zip module
description: |
    The Archive::Zip module allows a Perl program to create, manipulate, read, and write Zip archive file
builddeps  :
    - perl-test-mockmodule
    - perl-sub-identify
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
