name       : perl-archive-zip
version    : '1.59'
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PH/PHRED/Archive-Zip-1.59.tar.gz : 7a4b1b0aa43ae7231bb3212e86ab6b538725625df06e82772c3da24c8b26e75d
license    : Artistic-Perl-1.0
summary    : Perl Archive::Zip module
component  : programming.perl
description: |
    The Archive::Zip module allows a Perl program to create, manipulate, read, and write Zip archive file
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
