name       : perl-archive-zip
version    : '1.60'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/P/PH/PHRED/Archive-Zip-1.60.tar.gz : eac75b05f308e860aa860c3094aa4e7915d3d31080e953e49bc9c38130f5c20b
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : Perl Archive::Zip module
description: |
    The Archive::Zip module allows a Perl program to create, manipulate, read, and write Zip archive file
builddeps  :
    - perl-test-mockmodule
    - perl-super
    - perl-sub-identify
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-10860.patch
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
